#!/usr/bin/env node
// Generates supabase/seed.sql from src/data/questions.js content data.
// Run: node scripts/generate-seed.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { questions, gardens } from '../src/data/questions.js';
import { getFinePrint } from '../src/data/finePrint.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, '..', 'supabase', 'seed.sql');

// ── SQL literal helpers ──
// Escapes a string for use inside a single-quoted Postgres literal ('' doubling).
const sqlString = (value) => `'${String(value).replace(/'/g, "''")}'`;
// Returns a quoted literal, or the bare word NULL for nullish/empty values.
const sqlStringOrNull = (value) =>
  value === null || value === undefined || value === '' ? 'NULL' : sqlString(value);
const sqlInt = (value) => String(Number(value));

const lines = [];
const irregularities = [];

lines.push('-- Cilantro seed data');
lines.push('-- Auto-generated by scripts/generate-seed.mjs — do not edit by hand.');
lines.push(`-- Generated: ${new Date().toISOString()}`);
lines.push('-- Idempotent: safe to re-run (deletes prior seed rows first, FK-safe order).');
lines.push('');
lines.push('begin;');
lines.push('');

// ── Cleanup (FK-safe order: garden_items -> gardens, then seed questions) ──
lines.push('-- Cleanup prior seed data (FK-safe order)');
lines.push('delete from public.garden_items;');
lines.push('delete from public.gardens;');
lines.push(`delete from public.questions where source = 'seed';`);
lines.push('');

// ── Questions ──
lines.push('-- ══════════════════════════════════════════════════════════════');
lines.push('-- QUESTIONS');
lines.push('-- ══════════════════════════════════════════════════════════════');

let questionInsertCount = 0;
questions.forEach((q, i) => {
  if (!q.text) {
    irregularities.push(`questions[${i}] missing text: ${JSON.stringify(q)}`);
    return;
  }
  if (!q.vibe) {
    irregularities.push(`questions[${i}] missing vibe (text="${q.text}")`);
  }
  let difficulty = q.difficulty;
  if (difficulty === undefined || difficulty === null) {
    irregularities.push(`questions[${i}] missing difficulty (text="${q.text}"), defaulting to 1`);
    difficulty = 1;
  } else if (difficulty < 1 || difficulty > 3) {
    irregularities.push(`questions[${i}] difficulty out of range (${difficulty}), clamping (text="${q.text}")`);
    difficulty = Math.min(3, Math.max(1, difficulty));
  }

  const vibe = q.vibe || 'reflection';

  lines.push(
    `insert into public.questions (text, vibe, difficulty, fine_print, source, status, owner_id) values ` +
      `(${sqlString(q.text)}, ${sqlString(vibe)}, ${sqlInt(difficulty)}, ${sqlStringOrNull(getFinePrint(q.text))}, 'seed', 'published', NULL);`
  );
  questionInsertCount++;
});
lines.push('');

// ── Gardens + garden_items ──
lines.push('-- ══════════════════════════════════════════════════════════════');
lines.push('-- GARDENS');
lines.push('-- ══════════════════════════════════════════════════════════════');

let gardenInsertCount = 0;
gardens.forEach((g, gi) => {
  if (!g.id || !g.name) {
    irregularities.push(`gardens[${gi}] missing id/name: ${JSON.stringify(g)}`);
    return;
  }
  const description = g.description ?? '';
  const icon = g.icon ?? '';
  const color = g.color ?? '#a8a29e';
  const seedCost = g.seedCost ?? 100;
  const tier = g.tier ?? 1;

  lines.push(
    `insert into public.gardens (id, name, description, icon, color, seed_cost, tier, status, sort) values ` +
      `(${sqlString(g.id)}, ${sqlString(g.name)}, ${sqlString(description)}, ${sqlString(icon)}, ${sqlString(color)}, ${sqlInt(seedCost)}, ${sqlInt(tier)}, 'published', ${sqlInt(gi)});`
  );
  gardenInsertCount++;
});
lines.push('');

lines.push('-- ══════════════════════════════════════════════════════════════');
lines.push('-- GARDEN ITEMS');
lines.push('-- ══════════════════════════════════════════════════════════════');

let gardenItemInsertCount = 0;
const VALID_CONTENT_TYPES = new Set(['question', 'quote', 'vibe']);
gardens.forEach((g, gi) => {
  if (!g.id || !Array.isArray(g.items)) {
    if (!Array.isArray(g.items)) irregularities.push(`gardens[${gi}] (${g.id}) missing items array`);
    return;
  }
  g.items.forEach((item, ii) => {
    if (!item.text) {
      irregularities.push(`gardens[${gi}].items[${ii}] (${g.id}) missing text: ${JSON.stringify(item)}`);
      return;
    }
    let contentType = item.contentType;
    if (!VALID_CONTENT_TYPES.has(contentType)) {
      irregularities.push(
        `gardens[${gi}].items[${ii}] (${g.id}) invalid/missing contentType "${contentType}", defaulting to 'question'`
      );
      contentType = 'question';
    }
    let difficulty = item.difficulty;
    if (difficulty === undefined || difficulty === null) {
      irregularities.push(`gardens[${gi}].items[${ii}] (${g.id}) missing difficulty, defaulting to 1`);
      difficulty = 1;
    } else if (difficulty < 1 || difficulty > 3) {
      irregularities.push(`gardens[${gi}].items[${ii}] (${g.id}) difficulty out of range (${difficulty}), clamping`);
      difficulty = Math.min(3, Math.max(1, difficulty));
    }
    if (item.attribution === undefined && contentType === 'quote') {
      irregularities.push(`gardens[${gi}].items[${ii}] (${g.id}) quote missing attribution field`);
    }
    if (!item.vibe) {
      irregularities.push(`gardens[${gi}].items[${ii}] (${g.id}) missing vibe`);
    }

    lines.push(
      `insert into public.garden_items (garden_id, position, content_type, text, attribution, vibe, difficulty, fine_print) values ` +
        `(${sqlString(g.id)}, ${sqlInt(ii)}, ${sqlString(contentType)}, ${sqlString(item.text)}, ${sqlStringOrNull(item.attribution)}, ${sqlStringOrNull(item.vibe)}, ${sqlInt(difficulty)}, ${sqlStringOrNull(getFinePrint(item.text))});`
    );
    gardenItemInsertCount++;
  });
});
lines.push('');

lines.push('commit;');
lines.push('');

writeFileSync(outPath, lines.join('\n'), 'utf8');

console.log(`Wrote ${outPath}`);
console.log(`  questions inserted:    ${questionInsertCount}`);
console.log(`  gardens inserted:      ${gardenInsertCount}`);
console.log(`  garden_items inserted: ${gardenItemInsertCount}`);
if (irregularities.length) {
  console.log(`\nIrregularities found (${irregularities.length}):`);
  irregularities.forEach((msg) => console.log(`  - ${msg}`));
} else {
  console.log('\nNo data irregularities found.');
}
